Repository cscareerhub/megabot, pull requests merged in 2020-12, with the labels that each got.

#41 [misc] Add formatting script/shortcut and format project
  .github/workflows/ubuntu-test.yml
  README.md
  package.json
Labels: low priority

#36 [feature] The compensation bot responds to '++salary'
  .github/workflows/ubuntu-test.yml
  package.json
  specs/comp.spec.md
  src/bots/comp/constants.js
  src/bots/comp/embed.js
  src/bots/comp/index.js
  src/index.js
  yarn.lock
Labels: compensation, feature

#65 [feature] add in-memory database for testing
  package.json
  src/bots/ama/tests/addEvent.test.js
  src/bots/ama/tests/listEvents.test.js
Labels: feature
